spring:
  config:
    activate:
      on-profile: mock
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

whu-circle:
  auth:
    verification-code: "123456"
    token-expires-in: 7200
  mail:
    mode: mock
